### ISSUE TITLE
Bug Fix: Random crash doing normal scan operations

### ISSUE THREAD

**Issue by JeymyAV** [avan06/PS4CheaterNeo#32]
A new bug in the last version. 

1º I did a scan of some hex value in the executable and found 2 entries and this is ok, See below:
![image](https://github.com/avan06/PS4CheaterNeo/assets/9624829/48c4c6f8-9eff-4101-8cff-fe942322471a)

2º I click in the button refresh and after I click the button Next SCAN:
![image](https://github.com/avan06/PS4CheaterNeo/assets/9624829/b8162b44-77cf-4097-99f9-db9e1fbb1ec3)

As you can see this is wrong because the same 2 entries should be found cause I didn't change anything.

3º I continue click in the buttons Next SCAN and Refresh and after a few interactions:
![image](https://github.com/avan06/PS4CheaterNeo/assets/9624829/2e7bf691-902d-4485-8269-4664a20f5fa9)

The full log:
System.AggregateException: One or more errors occurred. ---> System.Exception: System.Exception: baseKey must be less than key, baseKey:109241798, key:109239156
   at PS4CheaterNeo.BitsDictionary.Add(UInt32 key, Byte[] data)
   at PS4CheaterNeo.Query.Comparer(Byte[] buffer, Section section, Int32 scanStep, UInt64 AddrMin, UInt64 AddrMax, BitsDictionary bitsDict, Boolean isCompareFirst, BitsDictionary bitsDictFirst)
   at PS4CheaterNeo.Query.<>c__DisplayClass33_3.<ScanTask>b__5()

System.AggregateException: One or more errors occurred. ---> System.Exception: baseKey must be less than key, baseKey:109241798, key:109239156
   at PS4CheaterNeo.Query.<>c__DisplayClass33_3.<ScanTask>b__5()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at PS4CheaterNeo.Query.<>c__DisplayClass33_0.<ScanTask>b__0()
---> (Inner Exception #0) System.Exception: baseKey must be less than key, baseKey:109241798, key:109239156
   at PS4CheaterNeo.Query.<>c__DisplayClass33_3.<ScanTask>b__5()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

   at PS4CheaterNeo.Query.<>c__DisplayClass33_0.<ScanTask>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PS4CheaterNeo.Query.<ScanTask>d__33.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Exception: System.Exception: baseKey must be less than key, baseKey:109241798, key:109239156
   at PS4CheaterNeo.BitsDictionary.Add(UInt32 key, Byte[] data)
   at PS4CheaterNeo.Query.Comparer(Byte[] buffer, Section section, Int32 scanStep, UInt64 AddrMin, UInt64 AddrMax, BitsDictionary bitsDict, Boolean isCompareFirst, BitsDictionary bitsDictFirst)
   at PS4CheaterNeo.Query.<>c__DisplayClass33_3.<ScanTask>b__5()

System.AggregateException: One or more errors occurred. ---> System.Exception: baseKey must be less than key, baseKey:109241798, key:109239156
   at PS4CheaterNeo.Query.<>c__DisplayClass33_3.<ScanTask>b__5()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at PS4CheaterNeo.Query.<>c__DisplayClass33_0.<ScanTask>b__0()
---> (Inner Exception #0) System.Exception: baseKey must be less than key, baseKey:109241798, key:109239156
   at PS4CheaterNeo.Query.<>c__DisplayClass33_3.<ScanTask>b__5()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

   at PS4CheaterNeo.Query.<>c__DisplayClass33_0.<ScanTask>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PS4CheaterNeo.Query.<ScanTask>d__33.MoveNext()<---

**Comment by JeymyAV** [comment]
More information about this bug:
I did the same test with the version PS4CheaterNeo-0.9.9.3 and this bug no happen, works correctly, so seems your last changes have broke something...

**Comment by avan06** [comment]
Hi, JeymyAV

Thank you for reporting the issue. It has been fixed in version [0.9.9.6-beta](https://github.com/avan06/PS4CheaterNeo/releases/tag/0.9.9.6-beta). Thank you.

**Comment by JeymyAV** [comment]
Most better but I have got yet the below crash following these steps:

1º First Scan
2º Refresh
3º Next Scan
4º Refresh + Next Scan + Stop and wait to finish. No results are returned. Correct until now, but then
5º Next Scan and the system raise error again. Below the crash log (but if you click ok on the button Window-Log, the correct results are returned):

System.AggregateException: One or more errors occurred. ---> System.Exception: System.Exception: baseKey must be less than key, baseKey:109471542, key:109468900
   at PS4CheaterNeo.BitsDictionary.Add(UInt32 key, Byte[] data)
   at PS4CheaterNeo.Query.Comparer(Byte[] buffer, Section section, Int32 scanStep, UInt64 AddrMin, UInt64 AddrMax, BitsDictionary bitsDict, Boolean isCompareFirst, BitsDictionary bitsDictFirst)
   at PS4CheaterNeo.Query.<>c__DisplayClass33_3.<ScanTask>b__5()

System.AggregateException: One or more errors occurred. ---> System.Exception: baseKey must be less than key, baseKey:109471542, key:109468900
   at PS4CheaterNeo.Query.<>c__DisplayClass33_3.<ScanTask>b__5()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at PS4CheaterNeo.Query.<>c__DisplayClass33_0.<ScanTask>b__0()
---> (Inner Exception #0) System.Exception: baseKey must be less than key, baseKey:109471542, key:109468900
   at PS4CheaterNeo.Query.<>c__DisplayClass33_3.<ScanTask>b__5()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---



   at PS4CheaterNeo.Query.<>c__DisplayClass33_0.<ScanTask>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PS4CheaterNeo.Query.<ScanTask>d__33.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Exception: System.Exception: baseKey must be less than key, baseKey:109471542, key:109468900
   at PS4CheaterNeo.BitsDictionary.Add(UInt32 key, Byte[] data)
   at PS4CheaterNeo.Query.Comparer(Byte[] buffer, Section section, Int32 scanStep, UInt64 AddrMin, UInt64 AddrMax, BitsDictionary bitsDict, Boolean isCompareFirst, BitsDictionary bitsDictFirst)
   at PS4CheaterNeo.Query.<>c__DisplayClass33_3.<ScanTask>b__5()

System.AggregateException: One or more errors occurred. ---> System.Exception: baseKey must be less than key, baseKey:109471542, key:109468900
   at PS4CheaterNeo.Query.<>c__DisplayClass33_3.<ScanTask>b__5()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at PS4CheaterNeo.Query.<>c__DisplayClass33_0.<ScanTask>b__0()
---> (Inner Exception #0) System.Exception: baseKey must be less than key, baseKey:109471542, key:109468900
   at PS4CheaterNeo.Query.<>c__DisplayClass33_3.<ScanTask>b__5()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---



   at PS4CheaterNeo.Query.<>c__DisplayClass33_0.<ScanTask>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PS4CheaterNeo.Query.<ScanTask>d__33.MoveNext()<---

**Comment by avan06** [comment]
I remember this error. After clicking the stop button, if you continue with the Next button, it may cause an error. However, if you click the Undo button after stopping, you should be able to continue the Next search. For now, please try this workaround, and I'll look into improving it when I have the time. Thank you.

**Comment by JeymyAV** [comment]
Yes, you are right, checked and the workaround works...
